- hosts: all
  tasks:
    - name: stop container
      shell:  docker container stop amol-container                    #name of container 
    - name: remove container
      shell: docker container rm amol-container
    - name: remove docker image
      shell: docker image rm thoratamol/docker-job                            #name of images (docker images)
    - name: create new container
      shell: docker container run -itd --name amol-container -p 9000:80 thoratamol/docker-job     #(docker-job>> name of jenkins job)
